version: '3'

services:
  node:
    container_name: node
    image: maestroi/nimiq-albatross:stable
    user: "1001:1001"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.node.rule=PathPrefix(`/`)"
      - "traefik.http.routers.node.entrypoints=http"
      - "traefik.http.services.node.loadbalancer.server.port=8648"
    environment:
      RPC_ENABLED: "true"
      NIMIQ_INSTANT_INBOUND: "true"
    volumes:
      - "/opt/nimiq/configuration/client.toml:/home/nimiq/.nimiq/client.toml"
    networks:
      - app_net

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    command: --interval 1800 node
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - app_net

  traefik:
    container_name: traefik
    image: traefik:v2.9.9
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
