{
 "title": "Nimiq",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Base stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Synced",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nimiq_consensus_is_established", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latest block number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nimiq_blockchain_block_number", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nimiq_watchdog_current_epoch", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Validator Activated Epoch",
   "type": "stat",
   "description": "Epoch for activation",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nimiq_activate_epoch", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"node-exporter:9100\",mode!=\"idle\"}[$__rate_interval])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"node-exporter:9100\"}[$__rate_interval])))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 7, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((avg_over_time(node_memory_MemAvailable_bytes{instance=\"node-exporter:9100\"}[$__rate_interval]) * 100) / avg_over_time(node_memory_MemTotal_bytes{instance=\"node-exporter:9100\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"node-exporter:9100\"} - node_boot_time_seconds{instance=\"node-exporter:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator address",
   "type": "stat",
   "description": "Validator address",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nimiq_activated_amount{}", "legendFormat": "{{address}}" }
   ]
  },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nimiq_watchdog_current_health", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Latest batch number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nimiq_watchdog_current_batch", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Peers connected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nimiq_network_peer_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nimiq_staking_active_validators",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"node-exporter:9100\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"node-exporter:9100\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Activation attempts",
   "type": "stat",
   "description": "Attempts of activation",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nimiq_activated_amount", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Restart attempts",
   "type": "stat",
   "description": "Restarted by watchdog",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nimiq_watchdog_container_restarts_total",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Nimiq Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Blockheight",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    { "expr": "nimiq_blockchain_block_number", "legendFormat": "Blockheight" }
   ]
  },
  {
   "title": "Peer count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "targets": [
    { "expr": "nimiq_network_peer_count", "legendFormat": "Peer Count" }
   ]
  },
  {
   "title": "Accounts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "targets": [
    { "expr": "nimiq_accounts_trie_accounts", "legendFormat": "Accounts" }
   ]
  },
  {
   "title": "Mempool TX",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "targets": [
    { "expr": "nimiq_mempool_tx_count", "legendFormat": "Mempool tx" }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Nimiq logs",
   "type": "logs",
   "gridPos": { "h": 20, "w": 15, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{container_name=\"/node\"}"
    }
   ]
  },
  {
   "title": "Validator Activator logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 18 },
   "targets": [
    {
     "expr": "{container_name=\"/activate_validator\"}",
     "maxLines": 500
    }
   ]
  },
  {
   "title": "Watchdog logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 29 },
   "targets": [
    {
     "expr": "{container_name=\"/nimiq-watchdog\"}",
     "maxLines": 500
    }
   ]
  }
 ]
}