[network]
peer_key_file = "peer_key.dat"
listen_addresses = [
	"/ip4/0.0.0.0/tcp/8443/ws",
]

seed_nodes = [
        { address = "/dns4/seed1.v2.nimiq-testnet.com/tcp/8443/ws" }
]

[consensus]
network = "dev-albatross"
min_peers = 1

[zkp]

# Specify the proof generation capabilities.

# Defines if the proof generation is active
# Default: false
# prover_active = true

# Defines the path for the proving and verifying keys folders
# Default: ".zkp"
prover_keys_path = "/home/nimiq/.zkp/"


[rpc-server]
# Bind the RPC server to specified IP
# Default: 127.0.0.1
bind="0.0.0.0"

# TCP-Port to use to create a listening socket for the JSON-RPC server.
# Possible values: any valid port number
# Default: 8648
port = 8648

# Allow only the RPC methods listed here. All methods are allowed if this is empty.
# Example: ["getBlockByNumber", "peerCount"],
# Default: []
methods = []

# Declare a username and password required to access the JSON-RPC server.
# Default: none
# username = "super"
# Default: none
# password = "secret"


[metrics-server]
# Bind the metrics server to the specified IP
# Default: 127.0.0.1
bind = "0.0.0.0"

# Port to use to create a listening socket for the metrics server.
# Possible values: any valid port number
# Default: 9100
port = 9200

# Declare a username and password required to access the metrics server.
# Default: none
# username = "super"

# Default: none
# password = "secret"

[database]

[log]
level = "info"
timestamps = true

[log.tags]
libp2p_swarm = "info"

[validator]
validator_address = "NQ07 0000 0000 0000 0000 0000 0000 0000 0000"
voting_key_file = "voting_key.dat"
fee_key_file = "fee_key.dat"
signing_key_file = "signing_key.dat"
