version: '3'

services:
  node:
    container_name: node
    image: maestroi/nimiq-albatross:stable
    user: "1001:1001"
    restart: unless-stopped
    ports:
      - "8443:8443"
    environment:
      RPC_ENABLED: "true"
      NIMIQ_INSTANT_INBOUND: "true"
    volumes:
      - "/opt/nimiq/configuration/client.toml:/home/nimiq/.nimiq/client.toml"
      - /opt/nimiq/data:/home/nimiq/.nimiq/testalbatross-history-consensus
    networks:
      - app_net

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    command: --interval 1800 node
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - app_net

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - "/opt/nimiq/configuration/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
