version: '3.7'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=http://192.168.50.101/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      # - grafana-storage:/var/lib/grafana
      - ./provisioning/prometheus.yml:/usr/share/grafana/conf/provisioning/datasources/prometheus.yml
      - ./provisioning/default_dashboards.yml:/usr/share/grafana/conf/provisioning/dashboards/default_dashboards.yml
      - ./provisioning:/usr/share/grafana/conf/provisioning
    networks:
      - app_net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-storage:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "127.0.0.1:9090:9090"
    networks:
      - app_net

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "127.0.0.1:9100:9100"
    networks:
      - app_net

volumes:
  grafana-storage:
  prometheus-storage:

networks:
  app_net:
    external: true
