global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node:9200']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'activator'
    static_configs:
      - targets: ['activate_validator:8000']
  - job_name: 'watchdog'
    static_configs:
      - targets: ['nimiq-watchdog:12345']
  - job_name: 'docker-monitor'
    static_configs:
      - targets: ['docker-monitor:8080']
