global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['node:9200']
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']
